import { defineConfig } from "vitepress";

export default defineConfig({
    title: "Phitter Docs",
    description: "Phitter documentation",
    head: [["link", { rel: "icon", href: "/logo.svg" }]],
    themeConfig: {
        logo: "/logo.svg",
        search: {
            provider: "local",
        },
        nav: [
            { text: "Documentation", link: "/documentation/intro/what-is-phitter" },
            { text: "Releases", link: "/release/release-main" },
            { text: "Phitter Web", link: "https://phitter.io/" },
            {
                text: "💚 Buy Me a Coffe",
                link: "https://buymeacoffee.com/sebastianjhm",
                target: "_blank",
            },
        ],
        sidebar: {
            "/documentation/": [
                {
                    text: "Introduction",
                    // collapsed: false,
                    items: [
                        { text: "What is Phitter?", link: "/documentation/intro/what-is-phitter" },
                        { text: "Installation", link: "/documentation/intro/installation" },
                        { text: "Examples", link: "/documentation/intro/examples" },
                        {
                            text: "☕ Buy Me a Coffee",
                            link: "https://www.buymeacoffee.com/tuusuario",
                            target: "_blank",
                        },
                    ],
                },
                {
                    text: "Fit",
                    items: [
                        { text: "Quick Fit", link: "/documentation/fit/quick-fit" },
                        { text: "Workers", link: "/documentation/fit/workers" },
                        {
                            text: "Goodness of fit",
                            collapsed: true,
                            items: [
                                { text: "Chi Sqaure", link: "documentation/fit/goodness-of-fit/chi-square" },
                                { text: "Kolomogorov Smirnov", link: "documentation/fit/goodness-of-fit/kolmogorov-smirnov.md" },
                                { text: "Anderson Darling", link: "documentation/fit/goodness-of-fit/anderson-darling" },
                            ],
                        },
                        {
                            text: "Continuous",
                            collapsed: true,
                            items: [
                                { text: "Continuous Implementation", link: "documentation/fit/continuous/continuous-fit-implementation" },
                                { text: "Continuous Fit Results", link: "documentation/fit/continuous/continuous-results" },
                            ],
                        },
                        {
                            text: "Discrete",
                            collapsed: true,
                            items: [
                                { text: "Discrete Implementation", link: "documentation/fit/discrete/discrete-fit-implementation" },
                                { text: "Discrete Fit Results", link: "documentation/fit/discrete/discrete-results" },
                            ],
                        },
                        { text: "Accelerate Fit", collapsed: true, items: [{ text: "Speed up for large datasets", link: "documentation/fit/accelerate/speed-up-large-datasets" }] },
                        {
                            text: "Plots",
                            collapsed: true,
                            items: [
                                { text: "Histogram", link: "documentation/fit/plots/plot-histogram" },
                                { text: "PDF Distribution", link: "documentation/fit/plots/plot-distribution" },
                                { text: "N Distributions", link: "documentation/fit/plots/plot-n-distributions" },
                                { text: "ECDF", link: "documentation/fit/plots/plot-ecdf" },
                                { text: "ECDF vs Distribution", link: "documentation/fit/plots/plot-ecdf-distribution" },
                                { text: "Quantile Quantile", link: "documentation/fit/plots/plot-qq" },
                                { text: "QQ vs Regression", link: "documentation/fit/plots/plot-qq-regression" },
                            ],
                        },
                    ],
                },
                {
                    text: "Simulation",
                    items: [
                        {
                            text: "Queue Simulation",
                            collapsed: true,
                            items: [
                                { text: "Own Distribution", link: "/documentation/simulation/queue-simulation/own-distribution" },
                                { text: "Create Queue Simulation Instance", link: "/documentation/simulation/queue-simulation/create-queue-instance" },
                                { text: "Run Queue Instance", link: "/documentation/simulation/queue-simulation/run-queue-simulation" },
                                { text: "Queue Simulation Metrics", link: "/documentation/simulation/queue-simulation/queue-metrics" },
                                { text: "Queue Simulation Probabilities", link: "/documentation/simulation/queue-simulation/queue-probabilities" },
                                { text: "Confidence Interval for Simulation Metrics", link: "/documentation/simulation/queue-simulation/queue-confidence-interval" },
                            ],
                        },
                        {
                            text: "Process Simulation",
                            collapsed: true,
                            items: [
                                { text: "Create Instance Simulation", link: "/documentation/simulation/process-simulation/create-instance-simulation" },
                                { text: "Create a Process Simulation", link: "/documentation/simulation/process-simulation/create-process" },
                                { text: "Graph Process Simulation", link: "/documentation/simulation/process-simulation/graph-process" },
                                { text: "Run a Process Simulation", link: "/documentation/simulation/process-simulation/run-simulation" },
                                { text: "Simulation Metrics", link: "/documentation/simulation/process-simulation/simulation-metrics" },
                                { text: "Confidence Interval of Metrics", link: "/documentation/simulation/process-simulation/confidence-interval" },
                            ],
                        },
                    ],
                },
                {
                    text: "Distributions",
                    items: [
                        { text: "Quick Example", link: "/documentation/distributions/quick-example" },
                        { text: "Continuous Distributions", link: "/documentation/distributions/continuous-distributions" },
                        { text: "Discrete Distributions", link: "/documentation/distributions/discrete-distributions" },
                        {
                            text: "Continuous",
                            collapsed: true,
                            items: [
                                { text: "Alpha", collapsed: true, link: "/documentation/distributions/continuous/alpha" },
                                { text: "Arcsine", collapsed: true, link: "/documentation/distributions/continuous/arcsine" },
                                { text: "Argus", collapsed: true, link: "/documentation/distributions/continuous/argus" },
                                { text: "Beta", collapsed: true, link: "/documentation/distributions/continuous/beta" },
                                { text: "Beta Prime", collapsed: true, link: "/documentation/distributions/continuous/beta-prime" },
                                { text: "Beta Prime 4P", collapsed: true, link: "/documentation/distributions/continuous/beta-prime-4p" },
                                { text: "Bradford", collapsed: true, link: "/documentation/distributions/continuous/bradford" },
                                { text: "Burr", collapsed: true, link: "/documentation/distributions/continuous/burr" },
                                { text: "Burr 4P", collapsed: true, link: "/documentation/distributions/continuous/burr-4p" },
                                { text: "Cauchy", collapsed: true, link: "/documentation/distributions/continuous/cauchy" },
                                { text: "Chi Square", collapsed: true, link: "/documentation/distributions/continuous/chi-square" },
                                { text: "Chi Square 3P", collapsed: true, link: "/documentation/distributions/continuous/chi-square-3p" },
                                { text: "Dagum", collapsed: true, link: "/documentation/distributions/continuous/dagum" },
                                { text: "Dagum 4P", collapsed: true, link: "/documentation/distributions/continuous/dagum-4p" },
                                { text: "Erlang", collapsed: true, link: "/documentation/distributions/continuous/erlang" },
                                { text: "Erlang 3P", collapsed: true, link: "/documentation/distributions/continuous/erlang-3p" },
                                { text: "Error Function", collapsed: true, link: "/documentation/distributions/continuous/error-function" },
                                { text: "Exponential", collapsed: true, link: "/documentation/distributions/continuous/exponential" },
                                { text: "Exponential 2P", collapsed: true, link: "/documentation/distributions/continuous/exponential-2p" },
                                { text: "F", collapsed: true, link: "/documentation/distributions/continuous/f" },
                                { text: "F 4P", collapsed: true, link: "/documentation/distributions/continuous/f-4p" },
                                { text: "Fatigue Life", collapsed: true, link: "/documentation/distributions/continuous/fatigue-life" },
                                { text: "Folded Normal", collapsed: true, link: "/documentation/distributions/continuous/folded-normal" },
                                { text: "Frechet", collapsed: true, link: "/documentation/distributions/continuous/frechet" },
                                { text: "Gamma", collapsed: true, link: "/documentation/distributions/continuous/gamma" },
                                { text: "Gamma 3P", collapsed: true, link: "/documentation/distributions/continuous/gamma-3p" },
                                { text: "Generalized Extreme Value", collapsed: true, link: "/documentation/distributions/continuous/generalized-extreme-value" },
                                { text: "Generalized Gamma", collapsed: true, link: "/documentation/distributions/continuous/generalized-gamma" },
                                { text: "Generalized Gamma 4P", collapsed: true, link: "/documentation/distributions/continuous/generalized-gamma-4p" },
                                { text: "Generalized Logistic", collapsed: true, link: "/documentation/distributions/continuous/generalized-logistic" },
                                { text: "Generalized Normal", collapsed: true, link: "/documentation/distributions/continuous/generalized-normal" },
                                { text: "Generalized Pareto", collapsed: true, link: "/documentation/distributions/continuous/generalized-pareto" },
                                { text: "Gibrat", collapsed: true, link: "/documentation/distributions/continuous/gibrat" },
                                { text: "Gumbel Left", collapsed: true, link: "/documentation/distributions/continuous/gumbel-left" },
                                { text: "Gumbel Right", collapsed: true, link: "/documentation/distributions/continuous/gumbel-right" },
                                { text: "Half Normal", collapsed: true, link: "/documentation/distributions/continuous/half-normal" },
                                { text: "Hyperbolic Secant", collapsed: true, link: "/documentation/distributions/continuous/hyperbolic-secant" },
                                { text: "Inverse Gamma", collapsed: true, link: "/documentation/distributions/continuous/inverse-gamma" },
                                { text: "Inverse Gamma 3P", collapsed: true, link: "/documentation/distributions/continuous/inverse-gamma-3p" },
                                { text: "Inverse Gaussian", collapsed: true, link: "/documentation/distributions/continuous/inverse-gaussian" },
                                { text: "Inverse Gaussian 3P", collapsed: true, link: "/documentation/distributions/continuous/inverse-gaussian-3p" },
                                { text: "Johnson SB", collapsed: true, link: "/documentation/distributions/continuous/johnson-sb" },
                                { text: "Johnson SU", collapsed: true, link: "/documentation/distributions/continuous/johnson-su" },
                                { text: "Kumaraswamy", collapsed: true, link: "/documentation/distributions/continuous/kumaraswamy" },
                                { text: "Laplace", collapsed: true, link: "/documentation/distributions/continuous/laplace" },
                                { text: "Levy", collapsed: true, link: "/documentation/distributions/continuous/levy" },
                                { text: "Loggamma", collapsed: true, link: "/documentation/distributions/continuous/loggamma" },
                                { text: "Logistic", collapsed: true, link: "/documentation/distributions/continuous/logistic" },
                                { text: "Loglogistic", collapsed: true, link: "/documentation/distributions/continuous/loglogistic" },
                                { text: "Loglogistic 3P", collapsed: true, link: "/documentation/distributions/continuous/loglogistic-3p" },
                                { text: "Lognormal", collapsed: true, link: "/documentation/distributions/continuous/lognormal" },
                                { text: "Maxwell", collapsed: true, link: "/documentation/distributions/continuous/maxwell" },
                                { text: "Moyal", collapsed: true, link: "/documentation/distributions/continuous/moyal" },
                                { text: "Nakagami", collapsed: true, link: "/documentation/distributions/continuous/nakagami" },
                                { text: "Non Central Chi Square", collapsed: true, link: "/documentation/distributions/continuous/non-central-chi-square" },
                                { text: "Non Central F", collapsed: true, link: "/documentation/distributions/continuous/non-central-f" },
                                { text: "Non Central T Student", collapsed: true, link: "/documentation/distributions/continuous/non-central-t-student" },
                                { text: "Normal", collapsed: true, link: "/documentation/distributions/continuous/normal" },
                                { text: "Pareto First Kind", collapsed: true, link: "/documentation/distributions/continuous/pareto-first-kind" },
                                { text: "Pareto Second Kind", collapsed: true, link: "/documentation/distributions/continuous/pareto-second-kind" },
                                { text: "Pert", collapsed: true, link: "/documentation/distributions/continuous/pert" },
                                { text: "Power Function", collapsed: true, link: "/documentation/distributions/continuous/power-function" },
                                { text: "Rayleigh", collapsed: true, link: "/documentation/distributions/continuous/rayleigh" },
                                { text: "Reciprocal", collapsed: true, link: "/documentation/distributions/continuous/reciprocal" },
                                { text: "Rice", collapsed: true, link: "/documentation/distributions/continuous/rice" },
                                { text: "Semicircular", collapsed: true, link: "/documentation/distributions/continuous/semicircular" },
                                { text: "T Student", collapsed: true, link: "/documentation/distributions/continuous/t-student" },
                                { text: "T Student 3P", collapsed: true, link: "/documentation/distributions/continuous/t-student-3p" },
                                { text: "Trapezoidal", collapsed: true, link: "/documentation/distributions/continuous/trapezoidal" },
                                { text: "Triangular", collapsed: true, link: "/documentation/distributions/continuous/triangular" },
                                { text: "Uniform", collapsed: true, link: "/documentation/distributions/continuous/uniform" },
                                { text: "Weibull", collapsed: true, link: "/documentation/distributions/continuous/weibull" },
                                { text: "Weibull 3P", collapsed: true, link: "/documentation/distributions/continuous/weibull-3p" },
                            ],
                        },
                        {
                            text: "Discrete",
                            collapsed: true,
                            items: [
                                { text: "Bernoulli", collapsed: true, link: "/documentation/distributions/discrete/bernoulli" },
                                { text: "Binomial", collapsed: true, link: "/documentation/distributions/discrete/binomial" },
                                { text: "Geometric", collapsed: true, link: "/documentation/distributions/discrete/geometric" },
                                { text: "Hypergeometric", collapsed: true, link: "/documentation/distributions/discrete/hypergeometric" },
                                { text: "Logarithmic", collapsed: true, link: "/documentation/distributions/discrete/logarithmic" },
                                { text: "Negative Binomial", collapsed: true, link: "/documentation/distributions/discrete/negative-binomial" },
                                { text: "Poisson", collapsed: true, link: "/documentation/distributions/discrete/poisson" },
                                { text: "Uniform", collapsed: true, link: "/documentation/distributions/discrete/uniform" },
                            ],
                        },
                    ],
                },
                {
                    text: "Benchmarks",
                    items: [
                        {
                            text: "Continuous",
                            collapsed: true,
                            items: [
                                { text: "Continuous fit time", link: "documentation/benchmarks/continuous/continuous-fit-time.md" },
                                { text: "Execute Continuous Fit", link: "documentation/benchmarks/continuous/continuous-parameters-estimation.md" },
                            ],
                        },
                        {
                            text: "Discrete",
                            collapsed: true,
                            items: [
                                { text: "Discrete Fit Implementation", link: "documentation/benchmarks/discrete/discrete-fit-time.md" },
                                { text: "Execute Discrete Fit", link: "documentation/benchmarks/discrete/discrete-parameters-estimation.md" },
                            ],
                        },
                    ],
                },
            ],
            "/release/": [
                {
                    //text: "Releases",
                    items: [
                        {
                            text: "Version 1",
                            collapsed: true,
                            items: [{ text: "Version 1.0", collapsed: true, items: [{ text: "What's new in v1.0.0", collapsed: true, link: "/release/v1/v1.0/v1.0.0" }] }],
                        },
                        {
                            text: "Version 0",
                            collapsed: true,
                            items: [{ text: "Version 0.7", collapsed: true, items: [{ text: "What's new in v0.7.2", collapsed: true, link: "/release/v0/v0.7/v0.7.2" }] }],
                        },
                    ],
                },
            ],
        },
        socialLinks: [
            { icon: "github", link: "https://github.com/phitter-core/phitter-kernel" },
            { icon: "youtube", link: "https://www.youtube.com/@phitter" },
            { icon: "x", link: "https://x.com/phitter__" },
        ],
    },
    markdown: {
        math: true,
    },
});
